Update to gstreamer 1.4.5, and many others.

diff --git a/yb_auto_build b/yb_auto_build
--- a/yb_auto_build
+++ b/yb_auto_build
@@ -118,6 +118,17 @@ global_cmake_args() {
     fi
 }
 
+remove_temps() {
+    case "$YB_NO_CLEAN" in
+    "0"|"false"|"")
+        rm -rf "$@";;
+    "1"|"true")
+        echo "YB_NO_CLEAN is true, not cleaning";;
+    *)
+        echo "Error: YB_NO_CLEAN should be 1 or true to disable post-build clean, 0, false, or empty to enable it"; exit 1;;
+    esac
+}
+
 default_build() {
     set_cflags $YB_WIDTH
     eval $YB_DEFAULT_BUILD_PRE_CONFIGURE_HOOK
@@ -183,7 +194,7 @@ lipo_build() {
         lipo -create $DESTDIR.32$PREFIX/$file $DESTDIR.64$PREFIX/$file -output $DESTDIR$PREFIX/$file
     done
 
-    rm -rf $DESTDIR.32 $DESTDIR.64 build-32.tmp build-64.tmp
+    remove_temps $DESTDIR.32 $DESTDIR.64 build-32.tmp build-64.tmp
 }
 
 #--------------- Main ----------------------------
@@ -198,7 +209,7 @@ then
     case `sw_vers -productVersion 2>/dev/null` in
         10.[78]*)
             MIN_MACOSX_VERSION=10.7;;
-        10.9*)
+        10.9*|10.10*)
             MIN_MACOSX_VERSION=10.9;;
         *) bs_abort "Unrecognized version of macosx";;
     esac
diff --git a/yb_download b/yb_download
--- a/yb_download
+++ b/yb_download
@@ -15,6 +15,54 @@ bs_abort() {
     exit 1
 }
 
+# Some projects live only in git, and github blacklists you if
+# you clone too often, so clone and save a tarball to the lan cache.
+
+# do_download_git repo commit [what-to-name-directory]
+do_download_git() {
+    _repo=$1
+    _commit=$2
+    _repodir=$3
+
+    if ! test "$YB_BUILDDIR"
+    then
+        bs_abort "You must set YB_BUILDDIR before calling yb_download"
+    fi
+    mkdir -p "$YB_BUILDDIR"
+    if ! test $_repodir
+    then
+        _repodir=`basename $_repo .git`
+    fi
+    DIRNAME=$_repodir
+
+    (
+    cd "$YB_BUILDDIR"
+
+    file=$_repodir.tar.gz
+
+    # First try to get it from our cache
+    if ! test -f "$YB_DOWNLOADS/$file"
+    then
+        if ! wget -P "$YB_DOWNLOADS" $YB_LANCACHE/$file
+        then
+            echo "Download from cache failed with $?, trying upstream"
+
+            git clone $_repo $_repodir
+            cd $_repodir
+            git reset --hard $_commit
+            cd ..
+
+            tar -czvf $file $_repodir
+            mkdir -p "$YB_DOWNLOADS"
+            cp $file "$YB_DOWNLOADS/$file"
+            rm -rf $file $_repodir
+            echo "To keep yourself from being blacklisted by the git server, copy $YB_DOWNLOADS/$file to $LANCACHE now"
+        fi
+    fi
+    tar -xzvf "$YB_DOWNLOADS/$file"
+    )
+}
+
 # Download a file.  If it's a tarball or zipfile, unpack it, too.
 # Usage:
 # do_download url [sha256sum [what-to-name-directory]]
@@ -22,6 +70,12 @@ do_download() {
     url=$1
     sha256=$2
     rename="$3"
+
+    if ! test "$YB_BUILDDIR"
+    then
+        bs_abort "You must set YB_BUILDDIR before calling yb_download"
+    fi
+
     mkdir -p "$YB_BUILDDIR"
     file=`echo $url | sed 's,.*/,,'`
 
@@ -33,6 +87,7 @@ do_download() {
         if ! wget -P "$YB_DOWNLOADS" $YB_LANCACHE/$file
         then
             echo "Download from cache failed with $?, trying upstream"
+            mkdir -p "$YB_DOWNLOADS"
             if ! wget -P "$YB_DOWNLOADS" $url
             then
                 echo "Download from upstream failed, retrying with delay"
@@ -66,6 +121,15 @@ do_download() {
     *.tar.zip) gzcat "$YB_DOWNLOADS/$file" | tar -C "$YB_BUILDDIR" -xf -;;   # FIXME: doesn't abort with bsdtar if file invalid
     *.zip) unzip -o "$YB_DOWNLOADS/$file" -d "$YB_BUILDDIR";;
     *.patch) ;;
+    *.7z)
+        # we're stuck with windows 7z on one machine
+        case `which 7z` in
+        *cygdrive*)
+            YB_DOWNLOADSW=`cygpath -w $YB_DOWNLOADS`
+            7z x -o"$YB_BUILDDIRW" "$YB_DOWNLOADSW\\$file";;
+        *)
+            7z x -o"$YB_BUILDDIR" "$YB_DOWNLOADS/$file";;
+        esac;;
     *) echo "what is a $file"; exit 1;;
     esac
 
@@ -89,15 +153,10 @@ fi
 YB_DOWNLOADS="${YB_DOWNLOADS:-$XDG_CACHE_HOME/yobuild}"
 YB_LANCACHE=${YB_LANCACHE:-http://yobuild/mirror}
 
-if ! test "$YB_BUILDDIR"
-then
-    bs_abort "You must set YB_BUILDDIR before calling yb_download"
-fi
-
 usage() {
     set +x
     cat << _EOF_
-Download and unpack a source package into $$YB_BUILDDIR
+Download and unpack a source package into \$YB_BUILDDIR
 Usage: $0 url [sha256sum [NEWNAME]]
 
 url must be the location of a .tgz, .tar.gz, .tar.bz2, .tar.xz, .tar.zip, .zip, or .patch file
@@ -121,6 +180,8 @@ case $1 in
     usage; exit 0;;
 ""|-*)
     usage; exit 1;;
+*.git)
+    do_download_git $1 $2 $3;;
 *)
-    do_download $1 $2 $3
+    do_download $1 $2 $3;;
 esac
diff --git a/yb_settings b/yb_settings
--- a/yb_settings
+++ b/yb_settings
@@ -30,3 +30,97 @@ DESTDIR=`cd $DESTDIR; pwd`
 
 mkdir -p $YB_OUTDIR
 YB_OUTDIR=`cd $YB_OUTDIR; pwd`
+
+yb_is_win() {
+    test -d /cygdrive/c/windows
+}
+
+if yb_is_win
+then
+  # Caution: cygpath may turn spaces into newlines, see kludge in winetricks?!
+  PREFIXW=`cygpath -w $PREFIX`
+  export PREFIXW
+  YB_BUILDDIRW=`cygpath -w $YB_BUILDDIR`
+  export YB_BUILDDIRW
+fi
+
+yb_abort() {
+    echo error: $@
+    exit 1
+}
+
+# If you didn't start cygwin from inside a visual studio 2010 command shell,
+# use this function to more or less do the same thing.  Fragile.
+yb_msvc2010_defaults() {
+    echo "Warning: No Visual C++ environment variables found, so making some up."
+    echo "Please start cygwin from a Visual Studio Command Prompt instead."
+    # Extracted by diffing environment between a cygwin shell started from
+    # visual studio 2010 command prompt and a normal cygwin shell.
+    export DevEnvDir='C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE'
+    # vs2010 uses .net internally
+    export Framework35Version=v3.5
+    export FrameworkDir=C:\Windows\Microsoft.NET\Framework\
+    export FrameworkDIR32=C:\Windows\Microsoft.NET\Framework\
+    export FrameworkVersion=v4.0.30319
+    export FrameworkVersion32=v4.0.30319
+    # boost needs these
+    export INCLUDE='C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include;'
+    export LIB='C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\lib;'
+    export LIBPATH='C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Windows\Microsoft.NET\Framework\v3.5;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\LIB;'
+
+    export PATH='/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/VSTSDB/Deploy:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/VC/BIN:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/Tools:/cygdrive/c/Windows/Microsoft.NET/Framework/v4.0.30319:/cygdrive/c/Windows/Microsoft.NET/Framework/v3.5:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/VC/VCPackages:/cygdrive/c/Program Files (x86)/HTML Help Workshop:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/Team Tools/Performance Tools:/cygdrive/c/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/bin/NETFX 4.0 Tools:/cygdrive/c/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/bin:/cygdrive/c/Program Files (x86)/Microsoft DirectX SDK (August 2006)/Utilities/Bin/x86:'$PATH
+    export VCINSTALLDIR='C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\'
+    export VSINSTALLDIR='C:\Program Files (x86)\Microsoft Visual Studio 10.0\'
+    export WindowsSdkDir='C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\'
+}
+
+yb_msvc2013_defaults() {
+    echo "Warning: No Visual C++ environment variables found, so making some up."
+    echo "Please start cygwin from a Visual Studio Command Prompt instead."
+    # Extracted by diffing environment between a cygwin shell started from
+    # visual studio 2013 command prompt and a normal cygwin shell.
+    export DevEnvDir='C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\'
+    export ExtensionSdkDir='C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1\ExtensionSDKs'
+    export Framework40Version='v4.0'
+    export FrameworkDir='C:\Windows\Microsoft.NET\Framework\'
+    export FrameworkDIR32='C:\Windows\Microsoft.NET\Framework\'
+    export FrameworkVersion='v4.0.30319'
+    export FrameworkVersion32='v4.0.30319'
+    # boost needs these
+    export INCLUDE='C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows Kits\8.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\winrt;'
+    export LIB='C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86;'
+    export LIBPATH='C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB;C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral;C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1\ExtensionSDKs\Microsoft.VCLibs\12.0\References\CommonConfiguration\neutral;'
+
+    export PATH='/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/CommonExtensions/Microsoft/TestWindow:/cygdrive/c/Program Files (x86)/MSBuild/12.0/bin:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/Tools:/cygdrive/c/Windows/Microsoft.NET/Framework/v4.0.30319:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/VCPackages:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/Team Tools/Performance Tools:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x86:/cygdrive/c/Program Files (x86)/Microsoft SDKs/Windows/v8.1A/bin/NETFX 4.5.1 Tools:'$PATH
+
+    export VCINSTALLDIR='C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\'
+    export VisualStudioVersion='12.0'
+    export VSINSTALLDIR='C:\Program Files (x86)\Microsoft Visual Studio 12.0\'
+    export WindowsSDK_ExecutablePath_x64='C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\x64\'
+    export WindowsSDK_ExecutablePath_x86='C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\'
+    export WindowsSdkDir='C:\Program Files (x86)\Windows Kits\8.1\'
+}
+
+# Make sure environment variables are already set for Visual C++,
+# or failing that, make a good guess.
+yb_vcvars32() {
+    case $PATH in
+    *"Visual Studio 10"*)
+        export YB_COMPILERNAME=msvc2010;;
+    *"Visual Studio 12"*)
+        export YB_COMPILERNAME=msvc2013;;
+    *Visual*)
+        yb_abort "Unknown version of visual C++ on path";;
+    *)
+        case "$YB_COMPILERNAME" in
+        msvc2010) yb_msvc2010_defaults;;
+        msvc2013) yb_msvc2013_defaults;;
+        *) yb_abort "unknown YB_COMPILERNAME $YB_COMPILERNAME";;
+        esac
+        ;;
+    esac
+    if ! yes | cl /help
+    then
+        yb_abort "Cannot run visual c++"
+    fi
+}
